//! Documentation evidence: the instruction files agent harnesses load, when
//! each one loads them, and what the repository's own files already show.
//! Parsers find and scope these files; Jev judges their sections.
pub mod discover;
pub mod load;
pub mod markdown;
pub mod overlap;
pub mod project;
pub mod references;

use anyhow::Result;
use std::{
    collections::{BTreeMap, BTreeSet},
    path::{Path, PathBuf},
};

/// Instruction files larger than this are listed, not read.
const MAX_BYTES: u64 = 1_048_576;

pub struct Repository {
    pub project: project::Project,
    /// Every regular instruction file with the harnesses that read it.
    pub readers: BTreeMap<PathBuf, Vec<load::Reader>>,
    /// Instruction files a generator writes; they count toward the context
    /// load but are judged at their source.
    pub generated: BTreeSet<PathBuf>,
    pub load: load::ContextLoad,
    /// Project documentation judged by the documentation rules: README,
    /// docs and other Markdown, without generated files.
    pub docs: BTreeSet<PathBuf>,
    pub root: PathBuf,
    /// Tracked, tagged and removed paths, for staleness candidates.
    pub history: crate::revision::History,
    /// Scripts and targets every tracked manifest declares.
    pub scripts: BTreeSet<String>,
}

impl Repository {
    /// Instruction files a documentation rule judges: some harness loads
    /// them, and no generator writes them.
    pub fn judged(&self, path: &Path) -> bool {
        self.readers.get(path).is_some_and(|r| !r.is_empty()) && !self.generated.contains(path)
    }
}

pub fn scan(root: &Path) -> Result<Repository> {
    let found = discover::discover(root)?;
    let sources: BTreeMap<PathBuf, String> = found
        .agent
        .iter()
        .filter(|p| std::fs::metadata(root.join(p)).is_ok_and(|m| m.len() <= MAX_BYTES))
        .filter_map(|p| Some((p.clone(), std::fs::read_to_string(root.join(p)).ok()?)))
        .collect();
    let generated_files: BTreeSet<PathBuf> = sources
        .iter()
        .filter(|(_, source)| generated(source))
        .map(|(p, _)| p.clone())
        .collect();
    let history = crate::revision::history(root);
    let files = load::files(sources, &found.links);
    let load = load::context_load(&files, &found.links, root);
    let links: BTreeSet<&PathBuf> = found.links.iter().map(|(p, _)| p).collect();
    let docs = found
        .project
        .iter()
        .filter(|p| {
            let path = root.join(p);
            path.symlink_metadata()
                .is_ok_and(|m| m.is_file() && m.len() <= MAX_BYTES)
                && std::fs::read_to_string(&path).is_ok_and(|s| !generated(&s))
        })
        .cloned()
        .collect();
    Ok(Repository {
        project: project::read(root, &found.directories),
        readers: files
            .into_iter()
            .filter(|f| !links.contains(&f.path))
            .map(|f| (f.path, f.readers))
            .collect(),
        generated: generated_files,
        load,
        docs,
        scripts: project::scripts(root, &history),
        history,
        root: root.to_path_buf(),
    })
}

/// A generator's marker in the first lines, such as those sync tools write
/// above each harness's copy of shared rules.
fn generated(source: &str) -> bool {
    crate::discovery::generated_header(source)
        || source
            .lines()
            .take(5)
            .any(|l| l.to_ascii_lowercase().contains("generated by"))
}
