//! Documentation evidence: the instruction files agent harnesses load, when
//! each one loads them, and what the repository's own files already show.
//! Parsers find and scope these files; Jev judges their sections.
pub mod discover;
pub mod format;
pub mod history;
pub mod load;
pub mod markdown;
pub mod overlap;
pub mod project;
pub mod references;

use anyhow::Result;
use std::{
    collections::{BTreeMap, BTreeSet},
    path::{Path, PathBuf},
};

/// Instruction files larger than this are listed, not read.
const MAX_BYTES: u64 = 1_048_576;

pub struct Repository {
    pub project: project::Project,
    /// Every regular instruction file with the harnesses that read it.
    pub readers: BTreeMap<PathBuf, Vec<load::Reader>>,
    /// Instruction files a generator writes; they count toward the context
    /// load but are judged at their source.
    pub generated: BTreeSet<PathBuf>,
    pub load: load::ContextLoad,
    /// Project documentation judged by the documentation rules: README,
    /// docs and other Markdown, without generated files.
    pub docs: BTreeSet<PathBuf>,
    pub root: PathBuf,
    /// Tracked, tagged and removed paths, for staleness candidates.
    pub history: history::History,
    /// Scripts and targets every tracked manifest declares.
    pub scripts: BTreeSet<String>,
}

impl Repository {
    /// Instruction files a documentation rule judges: some harness loads
    /// them, and no generator writes them.
    pub fn judged(&self, path: &Path) -> bool {
        self.readers.get(path).is_some_and(|r| !r.is_empty()) && !self.generated.contains(path)
    }
}

pub fn scan(root: &Path) -> Result<Repository> {
    let found = discover::discover(root)?;
    let sources = agent_sources(root, &found.agent);
    let generated_files: BTreeSet<PathBuf> = sources
        .iter()
        .filter(|(_, source)| generated(source))
        .map(|(p, _)| p.clone())
        .collect();
    let history = history::history(root);
    let files = load::files(sources, &found.links);
    let load = load::context_load(&files, &found.links, root);
    let links: BTreeSet<&PathBuf> = found.links.iter().map(|(p, _)| p).collect();
    Ok(Repository {
        project: project::read(root, &found.directories),
        readers: files
            .into_iter()
            .filter(|f| !links.contains(&f.path))
            .map(|f| (f.path, f.readers))
            .collect(),
        generated: generated_files,
        load,
        docs: project_docs(root, &found.project),
        scripts: project::scripts(root, &history),
        history,
        root: root.to_path_buf(),
    })
}

/// The text of each instruction file small enough to read.
fn agent_sources(root: &Path, paths: &BTreeSet<PathBuf>) -> BTreeMap<PathBuf, String> {
    paths
        .iter()
        .filter(|p| std::fs::metadata(root.join(p)).is_ok_and(|m| m.len() <= MAX_BYTES))
        .filter_map(|p| Some((p.clone(), std::fs::read_to_string(root.join(p)).ok()?)))
        .collect()
}

/// Project documents that are regular files small enough to read and that
/// no generator wrote.
fn project_docs(root: &Path, paths: &BTreeSet<PathBuf>) -> BTreeSet<PathBuf> {
    paths
        .iter()
        .filter(|p| {
            let path = root.join(p);
            path.symlink_metadata()
                .is_ok_and(|m| m.is_file() && m.len() <= MAX_BYTES)
                && std::fs::read_to_string(&path).is_ok_and(|s| !generated(&s))
        })
        .cloned()
        .collect()
}

/// A generator's marker in the first lines, such as those sync tools write
/// above each harness's copy of shared rules.
fn generated(source: &str) -> bool {
    crate::discovery::generated_header(source)
        || source
            .lines()
            .take(5)
            .any(|l| l.to_ascii_lowercase().contains("generated by"))
}

/// Phrases with which a project's README or CONTRIBUTING file says its
/// code is written for learners, as mini-redis ("intended to be a learning
/// resource", "Contributions should come with extensive comments") and wtf
/// ("built for educational purposes") do.
const TEACHING: [&str; 8] = [
    "educational purpose",
    "learning resource",
    "extensive comments",
    "demonstration project",
    "for teaching",
    "is teaching",
    "serves as a commentary",
    "all comments in this project",
];

/// Bytes of a README or CONTRIBUTING file read for the teaching phrases.
const TEACHING_READ_BYTES: u64 = 262_144;

/// Whether the repository at `root` says its code is written for learners,
/// so comments that explain what code does are its purpose.
pub fn teaching(root: &std::path::Path) -> bool {
    let Ok(entries) = std::fs::read_dir(root) else {
        return false;
    };
    entries.flatten().any(|entry| {
        let name = entry.file_name().to_string_lossy().to_lowercase();
        (name.starts_with("readme") || name.starts_with("contributing"))
            && crate::inventory::read_source(&entry.path(), TEACHING_READ_BYTES).is_ok_and(|text| {
                let text = text.to_lowercase();
                TEACHING.iter().any(|phrase| text.contains(phrase))
            })
    })
}

#[cfg(test)]
mod teaching_tests {
    #[test]
    fn a_readme_that_says_the_code_teaches_marks_a_teaching_project() {
        let project = crate::tests::Project::new();
        project.write("src/lib.rs", "fn f() {}\n");
        assert!(!super::teaching(&project.0));
        project.write(
            "README.md",
            "# Mini\n\nThis project is intended to be a learning resource for Tokio.\n",
        );
        assert!(super::teaching(&project.0));
        let other = crate::tests::Project::new();
        other.write(
            "CONTRIBUTING.md",
            "Contributions should come with extensive comments.\n",
        );
        assert!(super::teaching(&other.0));
    }
}
